// Design tokens sourced from DESIGN.md ("Protocol Investigative Interface")
// — read as reference and reproduced as the actual system, not copy/pasted
// markup. See docs/ux.md for how these are used across every screen.
import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#05070a",
        surface: "#0a0d14",
        "surface-bright": "#1f2636",
        "surface-container-lowest": "#040609",
        "surface-container-low": "#0d111a",
        "surface-container": "#121722",
        "surface-container-high": "#181f2e",
        "surface-container-highest": "#20293d",
        "surface-variant": "#1a2233",
        "on-surface": "#f1f5f9",
        "on-surface-variant": "#94a3b8",
        "inverse-surface": "#f1f5f9",
        "inverse-on-surface": "#0f172a",
        outline: "#334155",
        "outline-variant": "#1e293b",
        "surface-tint": "#00f5a0",
        primary: "#10b981",
        "on-primary": "#022c22",
        "primary-container": "#059669",
        "on-primary-container": "#ecfdf5",
        "inverse-primary": "#047857",
        "primary-fixed": "#34d399",
        "primary-fixed-dim": "#10b981",
        "on-primary-fixed": "#022c22",
        "on-primary-fixed-variant": "#064e3b",
        secondary: "#818cf8",
        "on-secondary": "#1e1b4b",
        "secondary-container": "#4f46e5",
        "on-secondary-container": "#e0e7ff",
        "secondary-fixed": "#a5b4fc",
        "secondary-fixed-dim": "#818cf8",
        "on-secondary-fixed": "#1e1b4b",
        "on-secondary-fixed-variant": "#3730a3",
        tertiary: "#fbbf24",
        "on-tertiary": "#451a03",
        "tertiary-container": "#d97706",
        "on-tertiary-container": "#fffbeb",
        "tertiary-fixed": "#fde68a",
        "tertiary-fixed-dim": "#fbbf24",
        "on-tertiary-fixed": "#451a03",
        "on-tertiary-fixed-variant": "#78350f",
        error: "#f43f5e",
        "on-error": "#4c0519",
        "error-container": "#be123c",
        "on-error-container": "#ffe4e6",
        background: "#07090e",
        "on-background": "#f1f5f9",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.625rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "16px",
        "stack-md": "16px",
        unit: "4px",
        "stack-sm": "8px",
        gutter: "12px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "data-label": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
